version: 2.1
jobs:
  build:
    docker:
     - image: jsii/superchain
    steps:
      - run:
          name: fix ssh permissions
          command: chmod 600 /root/.ssh/config
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm test
      - run:
          name: package
          command: npm run package
      - run:
          name: publish to pypi
          command: |
            scripts/publish-pypi.sh dist/python
      - run:
          name: publish to maven
          command: |
            scripts/publish-maven.sh dist/java
      - run:
          name: publish to nuget
          command: |
            scripts/publish-nuget.sh dist/dotnet

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
