version: 2.1
jobs:
  build:
    docker:
     - image: jsii/superchain
    steps:
      - run:
          name: fix ssh permissions
          command: chmod 600 /root/.ssh/config
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: npm run build && npm test
      - run:
          name: package
          command: npm run build && npm run package
      - run:
          name: publish to pypi
          command: |
            npx jsii-release-pypi dist/python
      - run:
          name: publish to nuget
          command: |
            npx jsii-release-nuget dist/dotnet
      - run:
          name: publish to maven
          command: |
            npx jsii-release-maven dist/java

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
